services:
  backend:
    image: authvault-enterprise-api
    container_name: authvault_api
    env_file:
      - ./api/.env
    depends_on:
      - redis

  frontend:
    image: authvault-enterprise-client
    container_name: authvault_client
    depends_on:
      - backend

  redis:
    image: redis:7-alpine
    container_name: authvault_redis

  nginx:
    image: nginx:stable-alpine
    container_name: authvault_nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend
