services:
  backend:
    image: authvault-enterprise-api
    container_name: authvault_api
    env_file:
      - ./api/.env
    depends_on:
      - redis
    ports:
      - "4000:4000"

  frontend:
    image: authvault-enterprise-client
    container_name: authvault_client
    ports:
      - "3000:80"
    depends_on:
      - backend

  redis:
    image: redis:7-alpine
    container_name: authvault_redis
    ports:
      - "6379:6379"
